build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.4

      services:
        rabbitmq: 3-management

      dependencies:
        before:
          - pecl install amqp
          - composer require --no-update gos/react-amqp:^0.3

      cache:
        disabled: false
        directories:
          - ~/.composer/cache

      project_setup:
        override: true

      tests:
        override:
          - php-scrutinizer-run

before_commands:
  - "composer update --no-dev --prefer-stable --prefer-source --classmap-authoritative"

tools:
  external_code_coverage:
    timeout: 3000
    runs: 4
