build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.4

      cache:
        disabled: false
        directories:
          - ~/.composer/cache

      project_setup:
        override: true

      tests:
        override:
          - php-scrutinizer-run

before_commands:
  - "composer install --no-dev --prefer-source -a"

tools:
  external_code_coverage:
    timeout: 3000
    runs: 2
